---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-service
  labels:
    app: init-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-service
  template:
    metadata:
      labels:
        app: init-service
    spec:
      containers:
        - name: init-service
          image: rishavrtwt/intervue_init_service:latest
          ports:
            - containerPort: 8000
            - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: init-service
spec:
  selector:
    app: init-service
  ports:
    - name: initserver
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: yjsserver
      protocol: TCP
      port: 1234
      targetPort: 1234
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          env:
            - name: REDIS_ADDR
              value: "redis:6379" # Address of the Redis instance
          ports:
            - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - protocol: TCP
      port: 9121
      targetPort: 9121
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestration
  labels:
    app: orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestration
  template:
    metadata:
      labels:
        app: orchestration
    spec:
      containers:
        - name: orchestration
          image: rishavrtwt/intervue_orchestration:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: orchestration
spec:
  selector:
    app: orchestration
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prohire
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: intervue.initservice.rishavrtwt.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: init-service
                port:
                  number: 8000
          - path: /yjs
            pathType: Prefix
            backend:
              service:
                name: init-service
                port:
                  number: 1234
