apiVersion: apps/v1
kind: Deployment
metadata:
  name: prohire
  labels:
    app: prohire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prohire
  template:
    metadata:
      labels:
        app: prohire
    spec:
      containers:
        - name: init-service
          image: rishavrtwt/intervue_init_service:latest
          ports:
            - containerPort: 8000
        - name: orchestration
          image: rishavrtwt/intervue_orchestration:latest
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: prohire
spec:
  selector:
    app: prohire
  ports:
    - protocol: TCP
      name: orchestration
      port: 3002
      targetPort: 3002
    - protocol: TCP
      name: init-service
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prohire
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: intervue.prohire.rishavrtwt.tech
      http:
        paths:
          - path: /orchestration
            pathType: Prefix
            backend:
              service:
                name: prohire
                port:
                  number: 3002
          - path: /init-service
            pathType: Prefix
            backend:
              service:
                name: prohire
                port:
                  number: 8000
